{% set name = "sfopenboson" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/SFOpenBoson-{{ version }}.tar.gz
  sha256: e7f44c420156d2a52ab6cc0c99475caf125dbbe7d697eba826ddbea93a97477c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.13
    - openfermion >=0.7
    - python >={{ python_min }}
    - scipy >=1.0.0
    - strawberryfields >=0.11

test:
  imports:
    - sfopenboson
    - sfopenboson.hamiltonians
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://xanadu.ai
  summary: Open source library for continuous-variable quantum computation
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://sfopenboson.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
